### ISSUE TITLE
Variable size and text for split traces

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#696]
The following works OK:

1. Create a scatter trace bill vs tips
2. Size it by size (note: this writes to data)
3. Set text=smoker
3. Split it by sex

The same thing in a different order doesn't work OK:

1. Create a scatter trace bill vs tips
2. Split it by sex
3. can't size it by size any more (not sure where it's writing but it's not the right place!)
4. can't set text any more (not sure where it's writing but it's not the right place!)

Maybe we should just prevent this, or maybe we should pick it up and write through to data or something... ? Not even sure what happens if you do it in grouped context.

/cc @VeraZab you're busy in the integration branch so let's get @dmt0 to look at this one and familiarize himself with the split trace issues, but just wanted to make sure you saw this

**Comment by dmt0** [comment]
Instead of writing to `data[].marker`, it writes to `transforms.styles[].value.marker`. 
Now say if data is split evenly into halves, than first half of sizes is given to each of the two split traces (do we have a name for those? 'subtrace'?). 

The options I see here are:
1. Don’t allow to set `attr`’s to arrays in subtraces.
2. When some `attr` is set to an array, write through to `data`, as you suggested, even if user specifically applied it to just one subtrace. This is doable. Perhaps we just need to check if payload has some `*src` in it, and pass stuff over to `data`. 
3. Apply the same split to the argument array and pass just the split part to the subtrace’s `attr` - that would be a more complete solution, giving the user full control over the subtraces. No idea how we would do that though. Might need help from plotly.js.

So I’d say (2) can be done for now, and we can think about (3) later. What do you think?

**Comment by VeraZab** [comment]
So the reason that for split traces i always write to `transforms.styles[].value.marker`, which styles individually each split, and not through inheritance from their parent, is because i wanted for things to work when switching from single to grouped context.

Ex. If you have a few splits all linked to one trace in data, and you go and style one of them more specifically, (so you write to `transforms.styles[].value.marker`), that will always take precedence over the style that's in the parent trace. So if you decided, in the grouped context, to write to `data[].marker`, that will only work for child split traces that didn't have a style set on them in `transforms.styles[].value.marker`. I wanted to keep that uniform, and so I worked with the premise that whatever style you can apply on parent, you can also individually apply it to split traces in their ``transforms.styles[].value` array.

If that is not the case, this is perhaps a plotly.js bug. Or some clarification on that would be needed. Have we tried this in a codepen?

**Comment by nicolaskruchten** [comment]
My feeling is that data arrays should be written back to the original trace in `data`... This is the most straightforward for us, and my guess is that this is what users will want to have happen anyway.
